# Generated by Django 4.2.7 on 2024-03-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commentbinarygrade',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_user_comment_grade'),
        ),
    ]
