# Generated by Django 4.2.7 on 2024-01-20 16:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import motomap.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('place_type', motomap.models.ChoiceArrayField(base_field=models.IntegerField(choices=[(100, 'Природное'), (200, 'Историческое'), (300, 'Техногенное')], default=100), size=None)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
