# Generated by Django 4.2.7 on 2024-01-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
